# Generated by Django 3.2.18 on 2023-05-21 15:21

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('question_type', models.CharField(choices=[('Accounts', "There's something wrong with my account"), ('Feedback', 'I would like to provide some feedback'), ('Complaint', 'I would like to make a complaint'), ('Technical issue', 'I would like to report a technical issue'), ('Other', 'Other')], default='Other', max_length=80)),
                ('subject', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('publication_date', models.DateField(auto_now_add=True, verbose_name='date published')),
                ('edited_date', models.DateField(auto_now=True)),
                ('ingredients', models.TextField(default=None)),
                ('instructions', models.TextField(default=None)),
                ('recipe_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('article_approved', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('taste_type', models.IntegerField(choices=[(None, 'Choose your taste'), (1, 'Sweet'), (2, 'Savoury')])),
                ('skill_level', models.IntegerField(choices=[(None, 'Choose diffucluty level'), (0, 'Easy'), (1, 'Intermediate'), (2, 'Advanced')])),
                ('preparation_time', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_post', to=settings.AUTH_USER_MODEL)),
                ('favourites', models.ManyToManyField(blank=True, related_name='blog_favourites', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='blog_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.recipe')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
