# Generated by Django 3.2.18 on 2023-05-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrequest',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contactrequest',
            name='last_name',
        ),
    ]
