# Generated by Django 3.2.18 on 2023-04-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230424_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='edited_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='publication_date',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
    ]
