# Generated by Django 3.2.18 on 2023-04-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='edited_date',
            field=models.DateField(auto_now=True),
        ),
    ]
