# Generated by Django 3.2.18 on 2023-04-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230428_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-publication_date']},
        ),
    ]
