# Generated by Django 3.2.18 on 2023-05-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-edited_date']},
        ),
    ]
