# Generated by Django 3.2.18 on 2023-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='edited_date',
            field=models.DateField(auto_now=True),
        ),
    ]
